services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: taskapi
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: taskapi
    ports: ["5432:5432"]
    volumes: [pg_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskapi"]
      interval: 5s

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "16686:16686"  # UI
      - "4318:4318"    # OTLP HTTP

volumes:
  pg_data:
